Strawberry_Cake=Checkbutton(Cake,text="Strawberry Cake",variable=var8,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkStrawberryCake)
Strawberry_Cake.grid(row=0,sticky=W)
PineappleCake=Checkbutton(Cake,text="Pineapple Cake",variable=var9,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkPineappleCake)
PineappleCake.grid(row=1,sticky=W)
BlackForestCake=Checkbutton(Cake,text="BlackForest Cake",variable=var10,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkBlackForestCake)
BlackForestCake.grid(row=2,sticky=W)
DarkChocalate_Cake=Checkbutton(Cake,text="DarkChocalate Cake",variable=var11,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkDarkChocalateCake)
DarkChocalate_Cake.grid(row=3,sticky=W)
RedVelvet_Cake=Checkbutton(Cake,text="RedVelvet Cake",variable=var12,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkRedVelvetCake)
RedVelvet_Cake.grid(row=4,sticky=W)
Mango_Cake=Checkbutton(Cake,text="Mango Cake",variable=var13,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkMangoCake)
Mango_Cake.grid(row=5,sticky=W)
Rasmalai_Cake=Checkbutton(Cake,text="Rasmalai Cake",variable=var14,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkRasmalaiCake)
Rasmalai_Cake.grid(row=6,sticky=W)

Strawberry_Cake1=Entry(Cake,font=("arial",16,"bold"),bd=3,width=6,justify=LEFT,state=DISABLED,textvariable=Strawberry_Cake2)
Strawberry_Cake1.grid(row=0,column=1)
PineappleCake1=Entry(Cake,font=("arial",16,"bold"),bd=3,width=6,justify=LEFT,state=DISABLED,textvariable=PineappleCake2)
PineappleCake1.grid(row=1,column=1)
BlackForestCake1=Entry(Cake,font=("arial",16,"bold"),bd=3,width=6,justify=LEFT,state=DISABLED,textvariable=BlackForestCake2)
BlackForestCake1.grid(row=2,column=1)
DarkChocalate_Cake1=Entry(Cake,font=("arial",16,"bold"),bd=3,width=6,justify=LEFT,state=DISABLED,textvariable=DarkChocalateCake2)
DarkChocalate_Cake1.grid(row=3,column=1)
RedVelvet_Cake1=Entry(Cake,font=("arial",16,"bold"),bd=3,width=6,justify=LEFT,state=DISABLED,textvariable=RedVelvet_Cake2)
RedVelvet_Cake1.grid(row=4,column=1)
Mango_Cake1=Entry(Cake,font=("arial",16,"bold"),bd=3,width=6,justify=LEFT,state=DISABLED,textvariable=Mango_Cake2)
Mango_Cake1.grid(row=5,column=1)
Rasmalai_Cake1=Entry(Cake,font=("arial",16,"bold"),bd=3,width=6,justify=LEFT,state=DISABLED,textvariable=Rasmalai_Cake2)
Rasmalai_Cake1.grid(row=6,column=1)

Tea=Checkbutton(Drinks,text="Tea",variable=var1,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkTea)
Tea.grid(row=0,sticky=W)
Milkshake=Checkbutton(Drinks,text="Milk Shake",variable=var2,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkMilkshake)
Milkshake.grid(row=1,sticky=W)
Falooda=Checkbutton(Drinks,text="Falooda",variable=var3,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkFalooda)
Falooda.grid(row=2,sticky=W)
Coffee=Checkbutton(Drinks,text="Coffee",variable=var4,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkCoffeee)
Coffee.grid(row=3,sticky=W)
Thumbshup=Checkbutton(Drinks,text="Thumbshup",variable=var5,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkthumbshup)
Thumbshup.grid(row=4,sticky=W)
Coke=Checkbutton(Drinks,text="Coke",variable=var6,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkcoke)
Coke.grid(row=5,sticky=W)
Orangejuice=Checkbutton(Drinks,text="Orangejuice",variable=var7,onvalue=1,offvalue=0,font=("arial",18,"bold"),bg='#a0522d',fg="#f4a460",command=chkorangejuce)
Orangejuice.grid(row=6,sticky=W)

Tea1=Entry(Drinks,font=("arial",16,"bold"),bd=3,width=6,state=DISABLED,justify=LEFT,textvariable=Tea2)
Tea1.grid(row=0,column=1)
Milkshake1=Entry(Drinks,font=("arial",16,"bold"),bd=3,width=6,state=DISABLED,justify=LEFT,textvariable=Milkshake2)
Milkshake1.grid(row=1,column=1)
Falooda1=Entry(Drinks,font=("arial",16,"bold"),bd=3,width=6,state=DISABLED,justify=LEFT,textvariable=Falooda2)
Falooda1.grid(row=2,column=1)
Coffee1=Entry(Drinks,font=("arial",16,"bold"),bd=3,width=6,state=DISABLED,justify=LEFT,textvariable=Coffee2)
Coffee1.grid(row=3,column=1)
Thumbshup1=Entry(Drinks,font=("arial",16,"bold"),bd=3,width=6,state=DISABLED,justify=LEFT,textvariable=Thumbshup2)
Thumbshup1.grid(row=4,column=1)
Coke1=Entry(Drinks,font=("arial",16,"bold"),bd=3,width=6,state=DISABLED,justify=LEFT,textvariable=Coke2)
Coke1.grid(row=5,column=1)
Orangejuice1=Entry(Drinks,font=("arial",16,"bold"),bd=3,width=6,state=DISABLED,justify=LEFT,textvariable=Orangejuice2)
Orangejuice1.grid(row=6,column=1)
#############Total cost##########################
lbl_costdrinks=Label(Cost_f,text="Cost Of Drinks   \t",bg='#a0522d',fg="#f4a460",font=("arial",14,"bold"))
lbl_costdrinks.grid(row=0,column=0,sticky=W)

text_costdrinks=Entry(Cost_f,insertwidth=2,bg="White",bd=7,font=("arial",14,"bold"),justify=RIGHT,textvariable=CostofDrinks)
text_costdrinks.grid(row=0,column=1)

lbl_costcake=Label(Cost_f,text="Cost Of Cake  \t",bg='#a0522d',fg="#f4a460",font=("arial",14,"bold"))
lbl_costcake.grid(row=1,column=0,sticky=W)

text_costcake=Entry(Cost_f,insertwidth=2,bg="White",bd=7,font=("arial",14,"bold"),justify=RIGHT,textvariable=CostofCake)
text_costcake.grid(row=1,column=1)

lbl_sc=Label(Cost_f,text="Service Charge  \t",bg='#a0522d',fg="#f4a460",font=("arial",14,"bold"))
lbl_sc.grid(row=2,column=0,sticky=W)

text_sc=Entry(Cost_f,insertwidth=2,bg="White",bd=7,font=("arial",14,"bold"),justify=RIGHT,textvariable=ServiceCharge)
text_sc.grid(row=2,column=1)
##############Payment##################

lbl_pt=Label(Cost_f,text="Paid tax \t",bg='#a0522d',fg="#f4a460",font=("arial",14,"bold"))
lbl_pt.grid(row=0,column=2,sticky=W)

text_pt=Entry(Cost_f,insertwidth=2,bg="White",bd=7,font=("arial",14,"bold"),justify=RIGHT,textvariable=Paidtax)
text_pt.grid(row=0,column=3)

lbl_st=Label(Cost_f,text="Sub Total  \t",bg='#a0522d',fg="#f4a460",font=("arial",14,"bold"))
lbl_st.grid(row=1,column=2,sticky=W)

text_st=Entry(Cost_f,insertwidth=2,bg="White",bd=7,font=("arial",14,"bold"),justify=RIGHT,textvariable=SubTotal)
text_st.grid(row=1,column=3)

lbl_tc=Label(Cost_f,text="Total Cost \t",bg='#a0522d',fg="#f4a460",font=("arial",14,"bold"))
lbl_tc.grid(row=2,column=2,sticky=W)

text_tc=Entry(Cost_f,insertwidth=2,bg="White",bd=7,font=("arial",14,"bold"),justify=RIGHT,textvariable=TotalCost)
text_tc.grid(row=2,column=3)
#############Reecipt##############
text_recipt=Text(Recipt_f,width=46,height=12,bg="White",bd=4,font=("arial",16,"bold"))
text_recipt.grid(row=0,column=0)
#buttons
total=Button(Bt,padx=16,pady=1,font=("arial",16,"bold"),width=4,text="Total",bg='#a0522d',fg="#f4a460",bd=7,command=CostOfItem)
total.grid(row=0,column=0)

Rceipt=Button(Bt,padx=16,pady=1,font=("arial",16,"bold"),width=4,text="Rceipt",bg='#a0522d',fg="#f4a460",bd=7,command=Recept)
Rceipt.grid(row=0,column=1)

Reset=Button(Bt,padx=16,pady=1,font=("arial",16,"bold"),width=4,text="Reset",bg='#a0522d',fg="#f4a460",bd=7,command=reset)
Reset.grid(row=0,column=2)

Exit=Button(Bt,padx=16,pady=1,font=("arial",16,"bold"),width=4,text="Exit",bg='#a0522d',fg="#f4a460",bd=7,command=exit)
Exit.grid(row=0,column=3)
